version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_PASS=licenta"
      - "RABBITMQ_DEFAULT_USER=licenta"

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=licenta
      - MONGO_INITDB_ROOT_PASSWORD=licenta
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  rabbitmqdata:
  mongodbdata:
